OpenLiberty/guide-gradle-intro

finish/build.gradle

Escape file path properly in openBrowser task

---

README.adoc

Add link to published website from repo

---

README.adoc

Changed description as suggested https://github.com/OpenLiberty/guides-common/issues/48

More descriptive description

---

README.adoc

Fixing https://github.com/OpenLiberty/guide-gradle-intro/issues/32

Readme updates

---

finish/src/main/liberty/config/server.xml
start/src/main/liberty/config/server.xml

Merge qa to master: update feature version

---

finish/build.gradle

#38
* Update build.gradle
* Update build.gradle
* Update build.gradle

Merge qa to master: Update dependency javax.servlet to 4.0 (#38)

---

README.adoc
finish/build.gradle
finish/src/test/java/io/openliberty/guides/hello/it/EndpointIT.java

Merge qa to master: use tags for hotspots

---

.travis.yml

https://github.com/OpenLiberty/guides-common/issues/277

Forced Trusty (#45)

---

.travis.yml
finish/src/main/java/io/openliberty/guides/hello/HelloServlet.java
start/src/main/java/io/openliberty/guides/hello/HelloServlet.java

Addressing https://github.com/OpenLiberty/guides-common/issues/291

Unnecessary comments

---

README.adoc
start/gradlew
start/gradlew.bat

https://github.com/OpenLiberty/guide-gradle-intro/issues/8
https://github.com/OpenLiberty/guide-gradle-intro/pull/55#pullrequestreview-321134616

gradle wrapper content

---

README.adoc

Connects to https://github.com/OpenLiberty/guide-gradle-intro/pull/60 SEO PR

address seo feedback

---

finish/build.gradle

Issue: https://github.com/OpenLiberty/guides-common/issues/419

change versions

---

.travis.yml
finish/build.gradle

Merge qa to master: fix travis automation

---

.travis.yml
CONTRIBUTING.md

Merge qa to master: update .travis.yml

---

.travis.yml

Merge qa to master: udpate .travis.yml

---

.travis.yml
scripts/travisTest.sh

LGP installed the released OL instead of the daily build

travis.yml cannot test the daily build correctly

---

.travis.yml
scripts/travisTest.sh

Merge qa to master: travis.yml cannot test the daily build correctly

---

.travis.yml
scripts/travisTest.sh

Merge qa to master: update travisTest.sh

---

scripts/travisTest.sh

Merge qa to maser: update travisTest.sh

---

README.adoc
scripts/travisTest.sh

PR: #90 
Issue: OpenLiberty/guides-common#514

Merge qa to master: add cd command

---

README.adoc

Addresses https://github.com/openliberty/guide-gradle-intro/issues/11
Other related issue: https://github.com/OpenLiberty/guide-maven-intro/issues/35
Related PR: https://github.com/OpenLiberty/guide-maven-intro/pull/98

Gradle Maven Compare
